name: Kwiki-Archive-Rcs
version: 0.15
abstract: Kwiki Page Archival Using RCS
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
